/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/wellness': typeof WellnessRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/wellness': typeof WellnessRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/wellness': typeof WellnessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accommodation'
    | '/auth'
    | '/book'
    | '/contact'
    | '/dining'
    | '/experiences'
    | '/gallery'
    | '/privacy'
    | '/wellness'
    | '/admin'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accommodation'
    | '/auth'
    | '/book'
    | '/contact'
    | '/dining'
    | '/experiences'
    | '/gallery'
    | '/privacy'
    | '/wellness'
    | '/admin'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accommodation'
    | '/auth'
    | '/book'
    | '/contact'
    | '/dining'
    | '/experiences'
    | '/gallery'
    | '/privacy'
    | '/wellness'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccommodationRoute: typeof AccommodationRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRoute
  ExperiencesRoute: typeof ExperiencesRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyRoute: typeof PrivacyRoute
  WellnessRoute: typeof WellnessRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccommodationRoute: AccommodationRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRoute,
  ExperiencesRoute: ExperiencesRoute,
  GalleryRoute: GalleryRoute,
  PrivacyRoute: PrivacyRoute,
  WellnessRoute: WellnessRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
